[package]
authors = ["James Waples <jamwaffles@gmail.com>"]
categories = ["embedded", "no-std"]
description = "I2C/SPI driver for the SSD1306 OLED display controller"
documentation = "https://docs.rs/ssd1306"
keywords = ["no-std", "ssd1306", "oled", "embedded", "embedded-hal-driver"]
license = "MIT OR Apache-2.0"
name = "ssd1306"
readme = "README.md"
repository = "https://github.com/jamwaffles/ssd1306"
version = "0.8.4"
edition = "2018"
exclude = [ "build.rs", "build.sh", "memory.x", "doc", "*.jpg", "*.png", "*.bmp" ]
rust-version = "1.61"

[badges]
circle-ci = { repository = "jamwaffles/ssd1306", branch = "master" }

[package.metadata.docs.rs]
targets = [ "thumbv7m-none-eabi", "thumbv7em-none-eabihf" ]

[dependencies]
display-interface = {git = "https://github.com/therealprof/display-interface/", rev = "7a8d3c4374dee567a8d86dfc4a884211ae1aee2f", package = "display-interface", version = "0.5.0-alpha.1", features = [
  "async",
  "nightly",
]}
display-interface-i2c = {git = "https://github.com/therealprof/display-interface/", rev = "7a8d3c4374dee567a8d86dfc4a884211ae1aee2f", package = "display-interface-i2c", version = "0.5.0-alpha.1", features = [
  "async",
  "nightly",
]}
display-interface-spi = {git = "https://github.com/therealprof/display-interface/", rev = "7a8d3c4374dee567a8d86dfc4a884211ae1aee2f", package = "display-interface-spi", version = "0.5.0-alpha.1", features = [
  "async",
  "nightly",
]}
embedded-hal = "0.2.7"
embedded-hal-async = "1.0.0-rc.1"
embedded-graphics-core = { version = "0.4.0", optional = true }

[dev-dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.7.3"
cortex-m-rtic = "1.1.4"
panic-halt = "0.2.0"
cast = { version = "0.2.6", default-features = false }
# Used to load BMP images in various examples
tinybmp = "0.5.0"
embedded-graphics = "0.8.0"
# Used by the noise_i2c examples
rand = { version = "0.8.4", default-features = false, features = [ "small_rng" ] }
stm32f1xx-hal = { version = "0.10.0", features = [ "rt", "stm32f103" ] }

[features]
default = ["graphics"]
graphics = ["embedded-graphics-core"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
debug = true
lto = true
